#
# Configuration
#

language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

notifications:
  email: true


sudo: required

branches:
  only:
  - master

install:
  - npm install
  - npm install ionic-app-lib
  - npm install -g ionic@beta

before_script:

script: 
  - npm postinstall
  - npm test

after_failure: cat /home/travis/build/udayakanth1122/ionic2-karma-jasmine-travis-seed-project/npm-debug.log

after_success:
  # push compiled TS to test folder in git for reference in coveralls
  - .travis/push_built_tests.sh
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # build for android
  - sudo npm install -g cordova ionic
  - sudo npm install -g ionic@beta
  - ionic state restore # install cordova stuff from package.json
