language: node_js
node_js:
- '4.0'
- '4.1'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
services:
before_install:
- npm update -g npm
- npm --version
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm install ionic-app-lib
- npm install --save-dev ionic
- npm install -g cordova
before_script:
script: npm test
notifications:
  email: true
after_failure: cat /home/travis/build/udayakanth1122/ionic2-karma-jasmine-travis-seed/npm-debug.log
branches:
  only:
  - master
env:
  matrix:
  - CXX=g++-4.8
after_success:
  # push compiled TS to test folder in git for reference in coveralls
  - .travis/push_built_tests.sh
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
