#
# Configuration
#

language: android

android:
  components:
    - android-23
    - build-tools-23.0.2
    - platform-tools

env:
  - CXX=g++-4.8

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: required

branches:
  only:
  - master

#
# Build Lifecycle:
#

before_install:
  - rm -rf /home/travis/.nvm                                         #
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -   # upgrade node manually as we're building on
  - sudo apt-get install -y nodejs                                   # android language and can't pick it in yml
  - sudo npm update -g npm
  # The following three lines came from angular-seed, unsure
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install ionic-app-lib

before_script:

script: npm test

after_failure: cat /home/travis/build/lathonez/clicker/npm-debug.log

after_success:
  # push compiled TS to test folder in git for reference in coveralls
  - .travis/push_built_tests.sh
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # build for android
  - sudo npm install -g cordova ionic
  - ionic state restore # install cordova stuff from package.json
  - ionic build android

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
